KYAU_Student_Info/KYAU_Student_Info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('view_club_details/<int:pk>', views.view_club_details, name='view_club_details'),
    path('apply_for_registration/<int:pk>', views.apply_for_registration, name='apply_for_registration'),
    path('general/', include('general.urls'))
]

KYAU_Student_Info/general/urls.py
from django.urls import path 
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'general'

urlpatterns = [
    path('login_page/', LoginView.as_view(template_name='general/login.html'), name='login_page'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('', views.index, name='index'),
    path('general_database/', views.general_database, name='general_database'),
    path('add_in_general_database/', views.add_in_general_database.as_view(), name='add_in_general_database'),

    path('club_details/<int:pk>', views.club_details, name='club_details'),
    path('application_list/<int:pk>', views.application_list, name='application_list'),
    path('application/<int:pk>/', views.application, name='application'),
    path('accept_application/<int:pk>/', views.accept_application, name='accept_application'),
    path('delete_application/<int:pk>/', views.delete_application, name='delete_application'),
]

KYAU_Student_Info/general/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    dept_name = models.CharField(max_length=50)
    class Meta():
        ordering = ['dept_name']
    def __str__(self):
        return self.dept_name

        
class Clubs(models.Model):
    club_name = models.CharField(max_length=50)
    club_desc = models.TextField(max_length=5000, default="")
    class Meta():
        ordering = ['club_name']
        verbose_name_plural = "All Clubs"
    def __str__(self):
        return self.club_name

class General_Database(models.Model):
    std_dept = models.ForeignKey(Department, on_delete=models.CASCADE)
    std_batch = models.IntegerField()
    std_name = models.CharField(max_length=50)
    std_id = models.BigIntegerField()
    std_email = models.EmailField(blank=True)
    club = models.ManyToManyField(Clubs, related_name='members', blank=True)

    class Meta():
        ordering = ['std_dept', 'std_batch', 'std_id']
        verbose_name_plural = "General_database"

    def __str__(self):
        return self.std_name




class Applications(models.Model):
    club = models.ForeignKey(Clubs, related_name='applications', on_delete=models.CASCADE)
    std_dept = models.ForeignKey(Department, on_delete=models.CASCADE)
    std_name = models.CharField(max_length=50)
    std_batch = models.IntegerField()
    std_id = models.CharField(max_length=50)
    std_email = models.EmailField()
    accept_membership = models.BooleanField(default=False)

    class Meta():
        ordering = ['club']
        verbose_name_plural = 'Applications'
    def __str__(self):
        return f"{self.club} Batch {self.std_batch} id:{self.std_id}"

KYAU_Student_Info/general/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView
from . import models
from KYAU_Student_Info import forms 
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
@login_required
def index(request):
    clubs = models.Clubs.objects.all()
    club_details = {}
    for club in clubs:
        club_details[club] = models.Applications.objects.filter(club__id=club.id).filter(accept_membership=True).count()
    dict = {'clubs': clubs, 'club_details': club_details }
    return render(request, 'general\index.html', dict)

@login_required
def general_database(request):
    all_clubs = models.Clubs.objects.all()
    all_students = models.General_Database.objects.all()

    students_with_clubs = []

    # Iterate over each student
    for student in all_students:
        clubs_for_student = student.club.all()  # Access clubs associated with the student
        students_with_clubs.append({'student': student, 'clubs': clubs_for_student})

    context = {'students_with_clubs': students_with_clubs, 'all_clubs': all_clubs}
    return render(request, 'general/general_database.html', context)

@method_decorator(login_required, name='dispatch')
class add_in_general_database(CreateView):
    form_class = forms.General_Database_Form
    success_url = reverse_lazy('general:general_database')
    # fields = ['std_dept','std_batch','std_name','std_id', 'std_email']
    template_name = 'general/add_in_general_database.html'
    context_object_name = 'form'

@login_required
def club_details(request, pk):
    club = models.Clubs.objects.get(pk=pk)
    no_of_application = models.Applications.objects.filter(club__id=pk).filter(accept_membership=False).count()
    club_members = models.Applications.objects.filter(club__id=pk).filter(accept_membership=True)
    no_of_members = club_members.count()
    dict = { 'club' : club , 'no_of_application' : no_of_application ,
             'club_members' : club_members , 'no_of_members': no_of_members}
    return render(request, 'general/club_details.html', dict )

@login_required
def application_list(request, pk):
    application_list = models.Applications.objects.filter(club__id=pk).filter(accept_membership=False)
    club_name = models.Clubs.objects.get(pk=pk)
    dict = {'application_list' : application_list, 'club_name' : club_name }
    return render(request, 'general/application_list.html', dict)


@login_required
def application(request, pk):
    application = models.Applications.objects.get(pk=pk)
    dict = {'application': application}
    return render(request, 'general/application.html', dict)

@login_required
def accept_application(request,pk):
    application = models.Applications.objects.get(pk=pk)
    application.accept_membership = True
    application.save()
    std = models.General_Database.objects.filter(std_dept=application.std_dept,
                                                  std_batch=application.std_batch, std_id=application.std_id).first()
    std.club.add(application.club.id)
    std.save()
    return redirect(reverse('general:application_list', kwargs={'pk': application.club.id }))

@login_required
def delete_application(request,pk):
    application = models.Applications.objects.get(pk=pk)
    club_id =  application.club.id
    application.delete()
    return redirect(reverse('general:application_list', kwargs={'pk': club_id }))


@method_decorator(login_required, name='dispatch')
class Create_Std_Info(CreateView):
    success_url = '/'
    model = models.General_Database
    fields = "__all__"
    template_name = 'general/create_std_info.html'

KYAU_Student_Info/general/templates/general/add_in_general_database.html
{% extends 'base.html' %}

{% block body %}


<div class="container mt-4 ">
    
    <div class="w-full sm:w-1/2 my-3 p-3 bg-body-secondary rounded-3">
        <form method="POST"> {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label for="{{field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

KYAU_Student_Info/general/templates/general/application.html
{% extends 'base.html' %}

{% block navitem %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'general:club_details' pk=application.club.id %}">Members</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'general:application_list' pk=application.club.id %}">Applications</a>
</li>
{% endblock %}

{% block body %}

<div class="container mt-5">
    
   <h4>Application to be registered in {{ application.club }} </h4>
    
    <div class="p-4 bg-body-tertiary rounded-3">
        <p class="text-success">Department : {{ application.std_dept }}</p>
        <p class="text-success">Name : {{ application.std_name }}</p>
        <p class="text-success">Batch : {{ application.std_batch }}</p>
        <p class="text-success">ID : {{ application.std_id }}</p>
        <p class="text-success">Email : {{ application.std_email }}</p>
        <div class="my-3">
            <a href="{% url 'general:accept_application' pk=application.id %}" class="btn btn-success btn-sm">Accept</a>
            <a href="{% url 'general:delete_application' pk=application.id %}" class="btn btn-danger btn-sm">Decline</a>
            <a href="{% url 'general:application_list' pk=application.club.id %}" class="btn btn-warning btn-sm">Keep pending</a>
        </div>
    </div>
</div>


{% endblock %}

KYAU_Student_Info/general/templates/general/application_list.html
{% extends 'base.html' %}

{% block navitem %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'general:club_details' pk=club_name.id %}">Members</a>
  </li>
{% endblock %}

{% block body %}

<div class="container mt-5">
    
   <h4>Applications to be registered in {{ club_name }}</h4>
    

    <table class="table table-bordered">
        <tr>
            <th>Dept</th>
            <th>Student Name</th>
            <th>Batch</th>
            <th>Id</th>
        </tr>
        {% for application in application_list %}
            <tr>
                <td>{{ application.std_dept }}</td>
                <td><a href="{% url 'general:application' pk=application.id %}">{{ application.std_name }}</a></td>
                <td>{{ application.std_batch }}</td>
                <td>{{ application.std_id }}</td>
            </tr>
        {% endfor %}
    </table>
</div>




{% endblock %}

KYAU_Student_Info/general/templates/general/club_details.html
{% extends 'base.html' %}

{% block body %}

{% if no_of_members %}
<h5 class="py-2 text-bg-secondary text-center rounded-3">All the members of {{ club }} total {{ no_of_members }}</h5>
    <div class="container mt-4  overflow-x-scroll">
        <table class="table table-bordered">
            <tr>
                <th>Department</th>
                <th>Name</th>
                <th>Batch</th>
                <th>ID</th>
                <th>Email</th>
            </tr>
            {% for member in club_members %}
                <tr>
                    <td>{{ member.std_dept }}</td>
                    <td>{{ member.std_name }}</td>
                    <td>{{ member.std_batch }}</td>
                    <td>{{ member.std_id }}</td>
                    <td>{{ member.std_email }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% else %}
<h5 class="py-2 text-bg-danger text-center rounded-3">No members in this club yet!!</h5>
{% endif %}

<div class="container my-5">
    <h5>Number of pending application : {{ no_of_application }} </h5>
    {% if no_of_application %}
    <a href="{% url 'general:application_list' pk=club.id %}" class="btn btn-secondary mt-3">See All Applications</a>
    {% endif %}
</div>


{% endblock %}

KYAU_Student_Info/general/templates/general/create_std_info.html
{% extends "base.html" %}

{% block body %}


<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit">
</form>


{% endblock %}

KYAU_Student_Info/general/templates/general/general_database.html
{% extends 'base.html' %}

{% block body %}

<div class="container mt-4">
<a href="{% url 'general:add_in_general_database' %}" class="btn btn-success">Add new student</a>
<h4 class="mt-2 text-center">List of KYAU students</h4>

<div class="overflow-x-auto">
    <table class="table table-bordered">
        <tr>
            <th>Department</th>
            <th>Batch</th>
            <th>Name</th>
            <th>ID</th>
            <th>Email</th>
            {% for club in all_clubs %}
            <th>{{ club.club_name }}</th>
            {% endfor %}
        </tr>
        {% for student_with_clubs in students_with_clubs %}
        <tr>
            <td>{{ student_with_clubs.student.std_dept }}</td>
            <td>{{ student_with_clubs.student.std_batch }}</td>
            <td>{{ student_with_clubs.student.std_name }}</td>
            <td>{{ student_with_clubs.student.std_id }}</td>
            <td>{{ student_with_clubs.student.std_email }}</td>
            {% for club in all_clubs %}
                {% if club in student_with_clubs.clubs %}
                    <td>Yes</td>
                {% else %}
                    <td></td>
                {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    
</div>

</div>



{% endblock %}

KYAU_Student_Info/general/templates/general/index.html
{% extends 'base.html' %}
{% block body %}

<h1 class="py-2 text-bg-success text-center">KYAU STUDENT CLUBS</h1>

    
        
        
<div class="container">
    {% for club, member_count in club_details.items %}
        <div class="my-3 mx-auto py-3 px-2 border-1 border rounded-3" style="max-width: 600px;">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ club }}</h5>
                <small class="text-body-secondary"><strong>{{ member_count }} Member{{ member_count|pluralize }}</strong></small>
            </div>
            <a href="{% url 'general:club_details' pk=club.id %}" class="my-3 btn btn-success btn-sm">View details</a>
        </div>
    {% endfor %}
</div>



{% endblock %}

KYAU_Student_Info/general/templates/general/login.html
{% extends 'base.html' %}
{% block body %}


<div class="container mt-5 ">
    <form action="" method="post">
        {% csrf_token %}
    
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{ form.password }}
        </div>
    
        {% if form.errors or form.non_field_error %}
            <div class="p-6 mb-3 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_error }}
                <p>Username and password doesn't match.</p>
            </div>
        {% endif %}
        <button type="submit" class="btn btn-success ">Submit</button>
    </form>
</div>










{% endblock %}