KYAU_Student_Info/KYAU_Student_Info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('view_club_details/<int:pk>', views.view_club_details, name='view_club_details'),
    path('apply_for_registration/<int:pk>', views.apply_for_registration, name='apply_for_registration'),
    path('general/', include('general.urls'))
]

KYAU_Student_Info/general/urls.py
from django.urls import path 
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'general'

urlpatterns = [
    path('login_page/', LoginView.as_view(template_name='general/login.html'), name='login_page'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('', views.index, name='index'),
    path('general_database/', views.general_database, name='general_database'),
    path('add_in_general_database/', views.add_in_general_database.as_view(), name='add_in_general_database'),

    path('club_details/<int:pk>', views.club_details, name='club_details'),
    path('application_list/<int:pk>', views.application_list, name='application_list'),
    path('application/<int:pk>/', views.application, name='application'),
    path('accept_application/<int:pk>/', views.accept_application, name='accept_application'),
    path('delete_application/<int:pk>/', views.delete_application, name='delete_application'),
]

KYAU_Student_Info/templates/apply_page.html
{% extends 'base.html' %}





{% block navitem %}
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'view_club_details' pk=club.id %}">Club_Details</a>
  </li>
{% endblock %}

{% block body %}

<div class="container mt-5">
    <h4 class="text-center">{{ club }}</h4>
    <div class="alert alert-warning">Your Department name, Batch and ID must be in the KYAU General Database</div>
    {% if not_in_database %}
    <div class="alert alert-danger">Your information didn't match with General Database!!! Try again.</div>
    {% endif %}
    
    
    <div class="w-full sm:w-1/2 my-3 p-3 bg-body-secondary rounded-3">
        <form method="POST"> {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label for="{{field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    
    
        {% if form.errors or form.non_field_errors %}
            <div class="p-6 mb-3 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}
    </div>

</div>


{% endblock %}

KYAU_Student_Info/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>

    {% block style %} {% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <script>
    </script>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">KYAU</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'general:general_database' %}">General_Database</a>
            </li>
            {% endif %}

            {% block navitem %} {% endblock %}  <!-- add nav item dynamically -->

          </ul>
          
          {% if user.is_authenticated %}
          <lis class="nav-items ms-auto me-lg-5">
            <a class="nav-link active" href="{% url 'general:logout' %}">Logout</a>
          </lis>
          {% else %}
          <lis class="nav-items ms-auto me-lg-5">
            <a class="nav-link active" href="{% url 'general:login_page' %}">Login</a>
          </lis>
          {% endif %}

        </div>
      </div>
    </nav>


      {% block body %}{% endblock %}
    
   

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

KYAU_Student_Info/templates/index.html
{% extends 'base.html' %}

{% block body %}

<h1 class="py-2 text-bg-success text-center">KYAU STUDENT CLUBS</h1>

    
        
        
<div class="container">
    {% for club, member_count in club_details.items %}
        <div class="my-3 mx-auto py-3 px-2 border-1 border rounded-3" style="max-width: 600px;">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ club }}</h5>
                <small class="text-body-secondary"><strong>{{ member_count }} Member{{ member_count|pluralize }}</strong></small>
            </div>
            <a href="{% url 'view_club_details' pk=club.id %}" class="my-3 btn btn-success btn-sm">View details</a>
            <a href="{% url 'apply_for_registration' pk=club.id %}" class="my-3 btn btn-success btn-sm">Apply</a>
        </div>
    {% endfor %}
</div>


{% endblock %}

KYAU_Student_Info/templates/view_club_details.html
{% extends 'base.html' %}

{% block body %}



    
        
        
<div class="container my-5">
    <a href="/" class="btn btn-secondary btn-sm">Home</a>
    <h4 class="py-2 text-success text-center ">{{ club.club_name }}</h4>
    <h6>{{ club.club_desc }}</h6>
    <h4>Total club members : <strong>{{ no_of_members }}</strong></h4>

    {% if no_of_members %}
    <h5>All Of Your Friends Who Are Member Of This Club</h5>
    <div class="overflow-x-scroll">
        <table class="table table-bordered">
            <tr>
                <th>Department</th>
                <th>Name</th>
                <th>Batch</th>
                <th>ID</th>
            </tr>
            {% for member in members %}
                <tr>
                    <td>{{ member.std_dept }}</td>
                    <td>{{ member.std_name }}</td>
                    <td>{{ member.std_batch }}</td>
                    <td>{{ member.std_id }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    {% endif %}

    <a href="{% url 'apply_for_registration' pk=club.id %}" class="my-3 btn btn-success btn-sm">Apply For Registration</a>
</div>


{% endblock %}